
DROP DATABASE IF EXISTS dreamlanddb;

CREATE DATABASE IF NOT EXISTS dreamlanddb DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP USER IF EXISTS 'dreamland';

CREATE USER 'dreamland'@'%' IDENTIFIED BY 'dreamland';

GRANT ALL PRIVILEGES ON dreamlanddb.* TO dreamland;

FLUSH PRIVILEGES;