spool create_dbuser.log

drop user dreamland cascade;
drop tablespace DREAMLAND_TBS including contents and datafiles cascade constraints;

--建表空间
CREATE TABLESPACE DREAMLAND_TBS
    LOGGING 
    DATAFILE 'DREAMLAND_TBS.DBF' SIZE 100M REUSE
    AUTOEXTEND 
    ON NEXT 10M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  AUTO;

--建用户
CREATE USER dreamland
  IDENTIFIED by "dreamland"
  DEFAULT TABLESPACE DREAMLAND_TBS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;
GRANT CONNECT TO dreamland;
GRANT RESOURCE TO dreamland;
GRANT CREATE ANY TABLE TO dreamland;
GRANT CREATE ANY VIEW TO dreamland;
GRANT CREATE DATABASE LINK TO dreamland;
GRANT CREATE TABLE TO dreamland;
GRANT DEBUG CONNECT SESSION TO dreamland;
GRANT DROP ANY TABLE TO dreamland;
GRANT SELECT ANY TABLE TO dreamland;
GRANT UNLIMITED TABLESPACE TO dreamland;
GRANT DBA TO dreamland;

spool off
exit;