spool create_dbuser.log

drop user gurms cascade;
drop tablespace GURMS_TBS including contents and datafiles cascade constraints;

--建表空间
CREATE TABLESPACE GURMS_TBS
    LOGGING 
    DATAFILE 'GURMS_TBS.DBF' SIZE 100M REUSE
    AUTOEXTEND 
    ON NEXT 10M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  AUTO;

--建用户
CREATE USER gurms
  IDENTIFIED by "gurms"
  DEFAULT TABLESPACE GURMS_TBS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;
GRANT CONNECT TO gurms;
GRANT RESOURCE TO gurms;
GRANT CREATE ANY TABLE TO gurms;
GRANT CREATE ANY VIEW TO gurms;
GRANT CREATE DATABASE LINK TO gurms;
GRANT CREATE TABLE TO gurms;
GRANT DEBUG CONNECT SESSION TO gurms;
GRANT DROP ANY TABLE TO gurms;
GRANT SELECT ANY TABLE TO gurms;
GRANT UNLIMITED TABLESPACE TO gurms;
GRANT DBA TO gurms;

spool off
exit;