spool create_dbuser.log

drop user oversky cascade;
drop tablespace OVERSKY_TBS including contents and datafiles cascade constraints;

--建表空间
CREATE TABLESPACE OVERSKY_TBS
    LOGGING 
    DATAFILE 'OVERSKY_TBS.DBF' SIZE 100M REUSE
    AUTOEXTEND 
    ON NEXT 10M EXTENT MANAGEMENT LOCAL SEGMENT 
    SPACE MANAGEMENT  AUTO;

--建用户
CREATE USER oversky
  IDENTIFIED by "oversky"
  DEFAULT TABLESPACE JIVF_TBS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;
GRANT CONNECT TO oversky;
GRANT RESOURCE TO oversky;
GRANT CREATE ANY TABLE TO oversky;
GRANT CREATE ANY VIEW TO oversky;
GRANT CREATE DATABASE LINK TO oversky;
GRANT CREATE TABLE TO oversky;
GRANT DEBUG CONNECT SESSION TO oversky;
GRANT DROP ANY TABLE TO oversky;
GRANT SELECT ANY TABLE TO oversky;
GRANT UNLIMITED TABLESPACE TO oversky;
GRANT DBA TO oversky;

spool off
exit;