export default
{
    KEY_USER: 'KEY_USER',
    KEY_DICT_CACHE: 'KEY_DICT_CACHE',
    EDIT_TYPE_INSERT:'INSERT',
    EDIT_TYPE_UPDATE:'UPDATE',
    EDIT_TYPE_DELETE:'DELETE',
    EDIT_TYPE_DETAIL:'DETAIL',
    TAB_SIZE: 10,
    PAGE_SIZE: 5,
    PAGE_SIZES: [5, 10, 20, 50]
}
